### ISSUE TITLE
App Engine Support?

### ISSUE THREAD

**Issue by drhoden** [googlemaps/google-maps-services-python#57]
I realize this isn't a code issue per say, but it would be really nice if this worked on App Engine out of the box (no dependencies).  Hey, while I'm at it, how about activation right within app.yaml's libraries section:

``` yaml
libraries:
- name: googlemaps
  version: latest
```
